<?php

return [
    "Prego", "Smartphone", "Barra de Proteína", "Teclado", "Mouse", "Monitor",
    "Cadeira", "Mesa", "Fone de Ouvido", "Carregador", "Câmera", "Notebook",
    "Tablet", "Impressora", "Mochila", "Caneta", "Lápis", "Caderno", "Livro",
    "Calculadora", "Bicicleta", "Capacete", "Relógio", "Óculos", "Sapato",
    "Camiseta", "Calça", "Jaqueta", "Bola", "Raquete", "Chuteira", "Tênis",
    "Sandália", "Chinelo", "Mala", "Ventilador", "Ar Condicionado", "Geladeira",
    "Fogão", "Micro-ondas", "Liquidificador", "Torradeira", "Panela", "Prato",
    "Copo", "Talher", "Toalha", "Lençol", "Travesseiro", "Colchão", "Sofá",
    "Estante", "Luminária", "Abajur", "Quadro", "Espelho", "Tapete", "Cortina",
    "Vaso", "Planta", "Flor", "Semente", "Adubo", "Regador", "Mangueira",
    "Tesoura", "Martelo", "Chave de Fenda", "Alicate", "Serrote", "Furadeira",
    "Parafuso", "Porca", "Arruela", "Dobradiça", "Fechadura", "Cadeado",
    "Extensão", "Tomada", "Interruptor", "Lâmpada", "Bateria", "Pilha",
    "Carro", "Moto", "Bateria de Carro", "Óleo de Motor", "Pneu", "Macaco",
    "Chave Inglesa", "Triângulo de Sinalização", "Estepe", "Rádio", "Alto-falante",
    "Amplificador", "Microfone", "Guitarra", "Violão", "Piano", "Teclado Musical",
    "Bateria (Instrumento)", "Flauta", "Saxofone", "Violino", "Cavaquinho",
    "Ukulele", "Baixo", "Mesa de Som", "Controladora DJ", "Fone de Retorno",
    "Pedal de Efeito", "Cabo de Áudio", "Suporte de Microfone", "Estante de Partitura",
    "Palheta", "Capotraste", "Afinador", "Metronomo", "Case para Instrumento",
    "Correia para Instrumento", "Encordoamento", "Baqueta", "Surdo", "Tamborim",
    "Pandeiro", "Cuíca", "Agogô", "Reco-reco", "Ganzá", "Maraca", "Clarinete",
    "Trompete", "Trombone", "Tuba", "Oboé", "Fagote", "Harmônica", "Acordeão",
    "Bandolim", "Banjo", "Harpa", "Lira", "Cítara", "Sitar", "Tabla", "Djembe",
    "Congas", "Bongo", "Timbal", "Cajón", "Castanhola", "Claves", "Cowbell",
    "Shekere", "Tambor de Mão", "Zabumba", "Alfaia", "Caixa de Guerra", "Repinique",
    "Tantã", "Rebolo", "Handpan", "Steel Drum", "Kalimba", "Didgeridoo", "Berimbau",
    "Caxixi", "Pandeirola", "Sino", "Triângulo", "Apito", "Whistle", "Kazoo",
    "Ocarina", "Melódica", "Clavinet", "Cravo", "Espineta", "Virginal", "Fortepiano",
    "Pianola", "Órgão", "Harmônio", "Sintetizador", "Sampler", "Drum Machine",
    "Sequenciador", "Workstation", "Controlador MIDI", "Interface de Áudio",
    "Monitor de Áudio", "Headphone", "Mixer", "Patchbay", "Rack", "Pedestal",
    "Pop Filter", "Shock Mount", "Spider", "Tela Acústica", "Isolador de Vibração",
    "Espuma Acústica", "Bass Trap", "Difusor", "Painel Acústico", "Cortina Acústica",
    "Porta Acústica", "Janela Acústica", "Piso Flutuante", "Carpete", "Vinil",
    "Laminado", "Porcelanato", "Cerâmica", "Granito", "Mármore", "Pedra",
    "Azulejo", "Pastilha", "Mosaico", "Papel de Parede", "Tinta", "Verniz",
    "Laca", "Esmalte", "Primer", "Selador", "Massa Corrida", "Massa Acrílica",
    "Rejunte", "Argamassa", "Cimento", "Areia", "Brita", "Cal", "Gesso",
    "Drywall", "Placa de Gesso", "Forro de PVC", "Forro de Isopor", "Forro de Madeira",
    "Sanca", "Rodapé", "Guarda-corpo", "Corrimão", "Parapeito", "Grade",
    "Portão", "Muro", "Cerca", "Tela", "Alambrado", "Concertina", "Cisterna",
    "Caixa d'Água", "Torneira", "Misturador", "Válvula", "Registro", "Sifão",
    "Canaleta", "Calha", "Ralo", "Vaso Sanitário", "Pia", "Lavatório", "Tanque",
    "Banheira", "Box", "Chuveiro", "Ducha", "Aquecedor", "Sauna", "Piscina",
    "Hidromassagem", "Spa", "Ofurô", "Deck", "Pergolado", "Gazebo", "Quiosque",
    "Churrasqueira", "Forno", "Fogareiro", "Lareira", "Aquecedor a Gás", "Aquecedor Elétrico",
];
